services:
  # zookeeper and kafka
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 1s
      timeout: 3s
      retries: 30

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
  #   depends_on:
  #     - kafka
  #   networks:
  #     - app-network

  # DATABASES
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: testservice
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  pg_restaurant_service:
    image: postgres:latest
    container_name: pg_restaurant_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: restaurantservice
    ports:
      - "5433:5432"
    volumes:
      - postgres_restaurant_data:/var/lib/postgresql/data
    networks:
      - app-network

  pg_order_service:
    image: postgres:latest
    container_name: pg_order_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: orderservice
    ports:
      - "5434:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql/data
    networks:
      - app-network

  pg_auth_service:
    image: postgres:latest
    container_name: pg_auth_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: authservice
    ports:
      - "5435:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - app-network

  pg_delivery_service:
    image: postgres:latest
    container_name: pg_delivery_service
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: deliveryservice
    ports:
      - "5436:5432"
    volumes:
      - postgres_delivery_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis_auth_service:
    container_name: redis_auth_service
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  redis_order_service:
    container_name: redis_order_service
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  # SERVICES
  restaurant-service:
    container_name: restaurant-service
    image: ghcr.io/softdev2425/mtogo-restaurantservice:latest
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      DATABASE_URL: postgresql://user:mypassword@pg_restaurant_service:5432/restaurantservice?schema=public
      KAFKA_BROKER: kafka:9092
      AUTH_SERVICE_URL: http://auth-service:3001
    depends_on:
      - pg_restaurant_service
      - kafka
    networks:
      - app-network

  order-service:
    container_name: order-service
    image: ghcr.io/softdev2425/mtogo-orderservice:latest
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      DATABASE_URL: postgresql://user:mypassword@pg_order_service:5432/orderservice?schema=public
      KAFKA_BROKER: kafka:9092
      AUTH_SERVICE_URL: http://auth-service:3001
      RESTAURANT_SERVICE_URL: http://restaurant-service:3002
      PAYMENT_SERVICE_URL: http://payment-service:3004
      REDIS_HOST: redis_order_service
      REDIS_PORT: 6379
    depends_on:
      - pg_order_service
      - redis_order_service
      - kafka
    networks:
      - app-network

  auth-service:
    container_name: auth-service
    image: ghcr.io/softdev2425/mtogo-authservice:latest
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgresql://user:mypassword@pg_auth_service:5432/authservice?schema=public
      LOCATION_IQ_API_KEY: ${LOCATION_IQ_API_KEY}
      REDIS_URL: redis://redis_auth_service:6379
    depends_on:
      - pg_auth_service
      - redis_auth_service
      - kafka
    networks:
      - app-network

  # API GATEWAY
  api-gateway:
    container_name: api-gateway
    image: ghcr.io/softdev2425/mtogo-api-gateway:latest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      AUTH_SERVICE_URL: http://auth-service:3001
      RESTAURANT_SERVICE_URL: http://restaurant-service:3002
      ORDER_SERVICE_URL: http://order-service:3003
      DELIVERY_SERVICE_URL: http://delivery-service:3006
      CLIENT_URL: http://localhost:3006
    depends_on:
      - order-service
    networks:
      - app-network

  # DELIVERY SERVICE
  delivery-service:
    container_name: delivery-service
    image: ghcr.io/softdev2425/mtogo-deliveryservice:latest
    ports:
      - "3006:3006"
    environment:
      PORT: 3006
      DATABASE_URL: postgresql://user:mypassword@pg_delivery_service:5432/deliveryservice?schema=public
      KAFKA_BROKER: kafka:9092
      ORDER_SERVICE_URL: http://order-service:3003
    depends_on:
      - pg_order_service
      - kafka
    networks:
      - app-network

  # PAYMENT SERVICE
  payment-service:
    container_name: payment-service
    image: ghcr.io/softdev2425/mtogo-paymentservice:latest
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
      PAYMENT_SERVICE_URL: http://payment-service:3004
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - kafka
    networks:
      - app-network

  notification-service:
    container_name: notification-service
    image: ghcr.io/softdev2425/mtogo-notificationservice:latest
    ports:
      - "3005:3005"
    environment:
      PORT: 3005
      KAFKA_BROKER: kafka:9092
      AUTH_SERVICE_URL: http://auth-service:3001
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
    depends_on:
      - pg_order_service
      - kafka
    networks:
      - app-network

  client:
    container_name: client
    image: ghcr.io/softdev2425/mtogo-client:latest
    ports:
      - "3030:3000"
    environment:
      VITE_REACT_APP_API_GATEWAY_URL: http://api-gateway:3000
    networks:
      - app-network

volumes:
  postgres_db_data:
  postgres_restaurant_data:
  postgres_auth_data:
  postgres_order_data:
  postgres_delivery_data:

networks:
  app-network:
    driver: bridge # Using bridge network for communication between containers
