services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword

  test-service:
    container_name: test-service
    image: ghcr.io/softdev2425/testservice:latest
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      POSTGRES_DB: testservice
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: postgres_db
      POSTGRES_PORT: 5432
      DATABASE_URL: postgresql://user:mypassword@postgres_db:5432/testservice?schema=public
    depends_on:
      - postgres_db

volumes:
  postgres_data:

networks:
  default:
    driver: bridge # Use bridge network for communication between containers

## pull each image from docker hub - services and dependencies
