global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "microservices"
    static_configs:
      - targets: ["auth-service:3001", "restaurant-service:3002", "order-service:3003", "delivery-service:3005"]
